language: python
dist: xenial
addons:
  apt:
    packages:
    - x11-utils
    - libxkbcommon-x11-0
services: xvfb
python:
- '3.7'
- '3.6'
env:
  matrix:
  - QT_API=PyQt5   PYTEST_QT_API=PyQt5
  - QT_API=PySide2 PYTEST_QT_API=PySide2
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: eyllanesc
  password:
    secure: T+iDrAETjaXQ/nuD957W7flh3fvKcWLfXFohnh6FR9UQ/vdcAYaWXNJivQujjeuKNb7O8KLebjfrMQCnI15/eFW7XKYhQiWE4RB2tovh7/azrHLQZW5+F5v2BPCYUe2lfuPys7LghwbepqyBGsl2+bFXIhO7rkXycT7TLusgT9nHMNF3DNuo8sit2kBY1opwjVW0EGN0gz5Jdbl7+YOCjwuGrlfjowfjzv7sZKxcjwg7KaR+dX5xBH7lV9ybZj5JTXOvdGSEifGPFtUTtFHTLMwj84liaCCkbJ5+Weg3fSAwOpiHGHcrPtycisKBKLTj8bV2oxd1Bg1C5xGVq12XqM8mFn+CUKAISU41OsW7n96e0kuF8mHjYdoTPWnhu0ywq2vC7m+zzDgbqOo1csC53jJGy5tjvYIDvUPFCSHwFaGtznxgynpZMUg/Kpd4og+qdEecgsE55wUfTyVj+WiNNAaqqFOhJaY7BIDnkZpa7fMguEp09kcJEJgiJsJNCtx8k6gcIlsRVkwMxoenawJcjvoWejThxsz1djcKnj9jLUcxUikzaSLmmNNBoF3Xl4184tAxnCimCjyaF8d7eVu7iZ9CW/XdugkKzsMI3OIp8v0TfeTP2nwTlynR6cQo6coJ8t2Im/R5EUz6/GIDqQ5tddWUO2X3ibn53Vg6kcGaWo4=
  on:
    tags: true
    repo: eyllanesc/qtmqtt
    python: 3.7
